# Generated by Django 3.2.8 on 2021-10-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productocomprado_idoriginalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
