# Generated by Django 3.2.8 on 2021-10-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('ProductList', models.ManyToManyField(to='api.ProductoComprado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
