# Generated by Django 3.2.8 on 2021-10-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
