# Generated by Django 3.2.8 on 2021-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apicarroscompraproductlist_ventaproductlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroscompraProductlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'api_carroscompra_productlist',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ApiCarroscompraProductlist',
        ),
    ]
